const ar = {
  home: 'الرئيسية',
  search: 'بحث',
  profile: 'الملف الشخصي',
  logout: 'تسجيل الخروج',
  login: 'تسجيل الدخول',
  title: 'مرحبا',
  // 'home-greeting': 'الصفحة الرئيسية',
  // 'profile-greeting': 'صفحة المستخدم',
  // 'search-greeting': 'صفحة البحث',
  // 'signUp-greeting': 'صفحة انشاء حساب',
  // 'logIn-greeting': 'صفحة تسجيل الدخول',
  notFound: 'عذراً الصفحة غير متوفرة',
  'home-main-services': 'الخدمات التي نوفرها.',
  contactMe: 'إتصل بي',
  review: 'أضف تقيماً',
  'review-message': 'تمت إضافة التقييم بنجاح',
  'review-error': 'يرجى إضافة تقييماً',
  'server-error': 'خطأ في الخادم',
  'review-exists': 'تمت إضافة التقييم من قبل',
  'content is required': 'يرجى إدخال المحتوى',
  // 'add-phoneNumber': ' أضف رقم الهاتف رجاءً', // line 93
  'add-review': 'صف تجربتك',
  ok: 'موافق',
  Cancel: 'إلغاء',
  // 'Phone-Number': 'رقم الهاتف', // line 86
  'write-review': 'أكتب تجربتك رجاءً',
  servicesOffer: 'الخدمات التي اقدمها ',
  'what-they-say-about-us': 'ماذا قالوا عنًا !',
  'user does not exist': 'المستخدم غير موجود',
  'home-search-location': 'ابحث حسب الموقع',
  'home-search-word': 'ابحث',
  'home-search-specific-location': 'مثال : بيت حانون',
  'home-welcome-search': 'ابحث عن الحرفي الأنسب لانجاز كل ما تحتاج.',
  city: 'اختر المدينة',
  'home-search-name': 'ابحث عن الاسم', // 'ابحث حسب الاسم'
  'home-join-us': 'انضم الى عالم الحرفيين الان', // "انضم الان الي عالم الحرفيين"
  'home-join-us-description': 'سجل الان واحصل على عضوية في مجتمعنا وقم بعرض خدماتك على اصحاب الاعمال',
  'home-join-us-button': 'سجل الآن',
  'error-heading': 'لقد حدث خطأ ما',
  'filter-heading': 'فلترة البحث',
  'login-title': 'تسجيل الدخول',
  // 'login-email': 'البريد الالكتروني', => email
  // 'login-password': 'كلمة المرور', => password
  'login-signup-text': 'إذا كنت لا تمتلك حساباً؟قم',
  'login-to-signup': 'بالتسجيل',
  'login-button': 'تسجيل دخول',
  'no-data': 'لا يوجد بيانات',
  'failed-login': 'بريد إلكتروني أو كلمة مرور خاطئة ..',
  'required-email': 'الرجاء إدخال البريد الإلكتروني!',
  'required-password': 'الرجاء إدخال كلمة المرور!',
  'invalid-email': 'البريد الإلكتروني غير صحيح',
  'invalid-password': 'يجب ألا تقل كلمة المرور عن ٨ أحرف',
  'error-message': 'حدث خطأ ما يرجى المحاولة لاحقا',
  'search-by-main-service': 'الخدمة الأساسية',
  'search-by-sub-service': 'الخدمة الفرعية',
  service: 'مثال: الحدادة',
  subService: 'مثال: حدادة أبواب',
  'search-name': 'مثال: محمد أحمد',
  'ok-button': 'تأكيد',
  'cancel-button': 'إلغاء',
  'delete-message-1': 'هل أنت متأكد من حذف هذا العمل؟',
  'successfully-delete': 'لقد تم حذف هذا العمل بنجاح',
  'successfully-delete-load': 'جاري الان حذف العمل ...',
  // 'error-delete-message': 'لقد حدث خطأ ما. حاول في وقت لاحق', //line 54
  'error-delete-message': 'لقد حدث خطأ ما. حاول في وقت لاحق',
  'edit-header': 'تعديل العمل',
  'title-of-work': 'عنوان العمل',
  'content-of-work': 'وصف العمل',
  'image-of-work': 'صورة العمل',
  'upload-image-of-work': 'اختيار الصورة',
  'successfully-edit': 'لقد تم تعديل العمل بنجاح',
  'error-edit': 'لقد حدث خطأ ما. حاول في وقت لاحق',
  'add-button': 'اضافة عمل',
  'title-required': 'الرجاء ادخال العنوان',
  'content-required': 'الرجاء ادخال الوصف',
  'image-required': 'الرجاء اختيار صورة',
  'text-title': 'عنوان العمل',
  'text-content': 'وصف العمل ',
  'successfully-added': 'لقد تم اضافة العمل بنجاح',
  'img-upload': 'يمكنك فقط اختيار صورة بصيغة JPG/PNG!',
  'First Name': 'الاسم الاول',
  'Last Name': 'الاسم الاخير',
  'Confirm Password': 'تأكيد كلمةالمرور',
  // 'Phone Number': 'رقم الهاتف', // line 86
  Address: 'العنوان',
  City: 'المدينة',
  Country: 'الدولة',
  'Zip Code': 'الرمز البريدي',
  'Sign Up': 'سجل',
  Register: 'تسجيل',
  'crate-account': 'إنشاء حساب',
  Next: 'التالي',
  'Email-exists': 'البريد الالكتروني مستخدم مسبقاً',
  'notMatch-Password': 'كلمة المرور غير متطابقة',
  'required-firstName': 'الرجاء إدخال الاسم الاول',
  'required-lastName': 'الرجاء إدخال الاسم الاخير',
  'required-confirmPassword': 'الرجاء تأكيد إدخال كلمة السر',
  locations: 'المواقع',
  footer: 'Herfa ©2022 فريق حرفة الفني',
  'all-services': 'الخدمات',
  'phone-number': 'رقم الجوال',
  'whats-app-placeholder': ' مثال: 00972590000000',
  'whats-app': ' الواتساب',
  'services-category': 'فئة الخدمات',
  services: 'الخدمات',
  location: 'الموقع',
  biography: 'نبذة تعريفية',
  'create-account-button': 'إنشاء حساب',
  'required-phone': 'الرجاء إدخال رقم الجوال!',
  'invalid-phone': 'رقم جوال غير صحيح!',
  'required-whatsapp': 'الرجاء إدخال واتس اب!',
  'phone-exists': 'رقم جوال مستخدم مسبقا!',
  'invalid-whatsapp': 'رقم واتس اب غير صحيح!',
  'required-service': 'الرجاء إختيار الخدمة!',
  'required-location': 'الرجاء إختيار الموقع!',
  'required-description': 'الرجاء إضافة نبذة عنك!',
  'previous-button': 'رجوع',
  'personal-information': 'البيانات الشخصية',
  'services-information': 'بيانات الخدمات',
  'log-in-email': 'مثال: example@gmail.com',
  'log-in-password': 'مثال سيئ: 12345678',
  'log-out': 'لقد تم تسجيل خروجك بنجاح!',
  'result-search': 'نتائج البحث :',
  // locations >>>>>>>>
  'Bait-hanoon': 'بيت حانون',
  'Bait-lahia': 'بيت لاهيا',
  'Jabalia-camp': 'معسكر جباليا',
  Jabalia: 'جباليا',
  Gaza: 'غزة',
  'Al-zahraa': 'النصيرات',
  'Al-nusirat': 'دير البلح',
  'Dair-albalah': 'دير البلح',
  'Al-maghazi': 'المغازي',
  'Al-buraig': 'البريج',
  'Khan-younis': 'خانيونس',
  Rafah: 'رفح',
  // services >>>>>>>>
  blacksmith: 'الحدادة',
  plumbing: 'السباكة',
  carpentry: 'النجارة',
  'construction-works': 'أعمال البناء',
  mechanics: 'ميكانيكا سيارات',
  electrical: 'الكهرباء',
  'paint-and-gypsum': 'أعمال الدهان والجبس',
  cleaning: 'أعمال التنظيف',
  gardening: 'أعمال الحدائق والبستنة',
  textile: 'أعمال النسيج',
  // subServices >>>>>>
  'general-blacksmithing': 'الحدادة العامة',
  doors: 'الأبواب',
  'fence-and-protection': 'السياج والحماية',
  'sewer-systems': 'شبكات المجاري',
  'healthy-water': 'المياه الصحية',
  'home-systems': 'تمديدات منزلية',
  furniture: 'الموبيليا',
  'wooden-doors': 'الابواب الخشبية',
  building: 'الطوبار',
  plastering: 'القصارة',
  flagstone: 'البلاط',
  'auto-mechanics': 'ميكانيكا السيارات',
  'auto-electricity': 'كهرباء السيارات',
  'general-electricity': 'الكهرباء العامة',
  'home-electricity': 'كهرباء المنازل',
  'renewable-energy-systems': 'الطاقة المتجددة',
  paints: 'دهانات',
  'metals-painting': 'دهانات المعادن',
  'wood-painting': 'دهانات الاخشاب',
  'gypsum-painting': 'دهانات الجبس',
  'dry-clean': 'دراي كلين',
  'carpet-cleaning': 'تنضيف السجاد',
  'institutions-cleaning': 'تنظيف المؤسسات',
  'tree-planting': 'زراعة الاشجار',
  garding: 'تشتيل المزارع',
  'pesticide-spraying': 'رش المبيدات',
  'fabrics-selling': 'بيع الأقمشة',
  sewing: 'الخياطة',
  'clothes-tailoring': 'تفصيل الملابس',
};

export default ar;
