const ar = {
  title: 'مرحبا',
  'home-greeting': 'الصفحة الرئيسية',
  'profile-greeting': 'صفحة المستخدم',
  'search-greeting': 'صفحة البحث',
  'signUp-greeting': 'صفحة انشاء حساب',
  'logIn-greeting': 'صفحة تسجيل الدخول',
  notFound: 'عذراً الصفحة غير متوفرة',
  'home-main-services': 'الخدمات التي نوفرها.',
  contactMe: 'إتصل بي',
  review: 'أضف تقيماً',
  'review-message': 'تمت إضافة التقييم بنجاح',
  'review-error': 'يرجى إضافة تقييماً',
  'server-error': 'خطأ في الخادم',
  'review-exists': 'تمت إضافة التقييم من قبل',
  'content is required': 'يرجى إدخال المحتوى',
  'add-phoneNumber': ' أضف رقم الهاتف رجاءً',
  'add-review': 'صف تجربتك',
  ok: 'موافق',
  Cancel: 'إلغاء',
  'Phone-Number': 'رقم الهاتف',
  'write-review': 'أكتب تجربتك رجاءً',
  servicesOffer: 'الخدمات التي اقدمها ',
  'what-they-say-about-us': 'ماذا قالوا عنًا !',
  'user does not exist': 'المستخدم غير موجود',
  'home-search-location': 'ابحث حسب الموقع',
  'home-search-word': 'ابحث',
  'home-search-specific-location': 'مثال : بيت حانون',
  'home-welcome-search': 'ابحث عن الحرفي الأنسب لانجاز كل ما تحتاج.',
  city: 'اختر المدينة',
  'home-search-name': 'ابحث عن الاسم',
  'home-join-us': 'انضم الى عالم الحرفيين الان',
  'home-join-us-description': 'سجل الان واحصل على عضوية في مجتمعنا وقم بعرض خدماتك على اصحاب الاعمال',
  'home-join-us-button': 'سجل الآن',
  'error-heading': 'لقد حدث خطأ ما',
  'filter-heading': 'فلترة البحث',
  'search-by-main-service': 'الخدمة الأساسية',
  'search-by-sub-service': 'الخدمة الفرعية',
  service: 'مثال: الحدادة',
  subService: 'مثال: حدادة أبواب',
  'search-name': 'مثال: محمد أحمد',
  'login-title': 'تسجيل الدخول',
  'login-email': 'البريد الالكتروني',
  'login-password': 'كلمة المرور',
  'login-signup-text': 'إذا كنت لا تمتلك حساباً؟قم',
  'login-to-signup': 'بالتسجيل',
  'login-button': 'تسجيل دخول',
};

export default ar;
