const en = {
  home: 'Home',
  search: 'Search',
  profile: 'Profile',
  logout: 'Logout',
  login: 'Login',
  title: 'Hello World',
  'home-greeting': 'Home Page',
  'profile-greeting': 'Profile Page',
  'search-greeting': 'Search Page',
  'signUp-greeting': 'Sign Up Page',
  'logIn-greeting': 'Log In Page',
  notFound: 'This page may have moved or is no longer available',
  notFoundDescription: 'Sorry,  we can\'t find the page you requested',
  goHome: 'Go To Home',
  'home-main-services': 'The services we provide.',
  contactMe: 'Contact me',
  'Phone-Number': 'Phone Number',
  'write-review': 'Write a review please',
  'login-title': 'Log In',
  'login-email': 'Email',
  'login-password': 'Password',
  'login-signup-text': 'don\'t have an account?',
  'login-to-signup': 'Sign Up',
  'login-button': 'Submit',
  'no-data': 'No data',
  'failed-login': 'incorrect Email or Password ..',
  'required-email': 'Please input your email!',
  'required-password': 'Please input your password!',
  'invalid-email': 'email is not a valid email',
  'invalid-password': 'password must be at least 8 characters',
  'error-message': 'something went wrong try again later',
  review: 'Add a review',
  'add-review': 'Add a review',
  'review-message': 'Review added successfully',
  'add-phoneNumber': 'Please add your phone number',
  'review-exists': 'You have already added a review',
  'content is required': 'Please enter the content',
  'review-error': 'Please add a review',
  'server-error': 'Internal Server Error',
  ok: 'Ok',
  Cancel: 'Cancel',
  servicesOffer: 'The services I offer',
  'what-they-say-about-us': 'What they said about us !',
  'user does not exist': 'User does not exist',
  'home-search-location': 'Search By location',
  'home-search-word': 'Search',
  'home-search-specific-location': 'Example: Bait-hanoon',
  'home-welcome-search': 'Search for the most suitable craftsman to get everything you need done.',
  city: 'choose the city',
  'home-search-name': 'Search for by name',
  'home-join-us': 'Join the world of craftsmen now',
  'home-join-us-description': 'Register now and become a member of our community and offer your services to business owners',
  'home-join-us-button': 'Register Now',
  'error-heading': 'There is ERROR occurred',
  'filter-heading': 'Search Filter',
  'search-by-main-service': 'Main Service',
  'search-by-sub-service': 'Sub Services',
  service: 'Example: Blacksmith',
  subService: 'Example: doors',
  'search-name': 'Example: Mohammed Ahmed',
  'ok-button': 'Ok',
  'cancel-button': 'Cancel',
  'delete-message-1': 'Are you sure that you want to delete this work?',
  'successfully-delete': 'Your work deleted successfully',
  'error-delete-message': 'An error ocurred.please try later',
  'edit-header': 'Edit this work',
  'title-of-work': 'Title of work',
  'content-of-work': 'Description of work',
  'image-of-work': 'Image of work',
  'upload-image-of-work': 'Select Image',
  'successfully-edit': 'Your work edited successfully',
  'error-edit': 'An error ocurred.Please try later',
  'add-button': 'Add Work',
  'title-required': 'Please enter title!',
  'content-required': 'Please enter description!',
  'image-required': 'Please select image!',
  'text-title': 'Work title',
  'text-content': 'Work description',
  'successfully-added': 'The work added successfully',
  'img-upload': 'You can only upload JPG/PNG images!',
  'successfully-delete-load': 'Delete loading',
  'First Name': 'First Name',
  'Last Name': 'Last Name',
  Email: 'Email',
  Password: 'Password',
  'Confirm Password': 'Confirm Password',
  'Phone Number': 'Phone Number',
  'Sign Up': 'Sign Up As A Pro',
  Register: 'Register',
  'crate-account': 'Create an account',
  Next: 'Next',
  errorMsg: 'Error',
  'Email-exists': 'Email already exists',
  'notMatch-Password': 'Not Match Password',
  'required-firstName': 'Please input your first name!',
  'required-lastName': 'Please input your last name!',
  'required-confirmPassword': 'Please input your confirm password!',
  locations: 'Locations',
  footer: 'Herfa ©2022 Created By Herfa Team',
  'all-services': 'services',
  'phone-number': 'Phone Number',
  'whats-app-placeholder': 'Example: 00972590000000',
  'whats-app': 'Whatsapp',
  'services-category': 'Services Category',
  services: 'Services',
  location: 'Location',
  biography: 'Biography',
  'create-account-button': 'Create Account',
  'required-phone': 'please enter a phone number!',
  'invalid-phone': 'incorrect phone number!',
  'phone-exists': 'phone is already exists!',
  'required-whatsapp': 'Please enter whatsApp!',
  'invalid-whatsapp': 'incorrect whatsApp number!',
  'required-service': 'Please select the service!',
  'required-location': 'Please select the location!',
  'required-description': 'Please add a biography!',
  'previous-button': 'Previous',
  'personal-information': 'Personal Information',
  'services-information': 'Services Information',
  'log-in-email': 'Example: example@gmail.com',
  'log-in-password': 'Bad Example: 12345678',
  'log-out': 'Logged out successfully !',
  'result-search': 'Search Result :',
  'north-gaza': 'North Gaza',
  gaza: 'Gaza Governorate',
  'central-governorate': 'Central Governorate',
  'south-gaza': 'South Gaza',
  // locations >>>>>>>>>
  'بيت حانون': 'Bait-hanoon',
  'بيت لاهيا': 'Bait-lahia',
  'معسكر جباليا': 'Jabalia-camp',
  'جباليا ': 'Jabalia',
  غزة: 'Gaza', // check quotes
  الزهراء: 'Al-zahraa',
  النصيرات: 'Al-nusirat',
  'دير البلح': 'Dair-albalah',
  المغازي: 'Al-maghazi',
  البريج: 'Al-buraig',
  خانيونس: 'Khan-younis',
  رفح: 'Rafah',
  // services >>>>>>>>
  الحدادة: 'Blacksmith',
  السباكة: 'Plumbing',
  النجارة: 'Carpentry',
  'اعمال البناء': 'Construction works',
  'ميكانيكي سيارات': 'Mechanics',
  كهربائي: 'Electrical',
  'اعمال الدهان والجبس': 'Paint and Gypsum',
  'اعمال التنضيف': 'Cleaning',
  'حدائق وبستنة': 'Gardening',
  'اعمال النسيج': 'Textile',
  // subServices >>>>>>>>
  'الحدادة العامة': 'General Blacksmithing',
  الابواب: 'doors',
  'السياج والحماية': 'Fence and Protection',
  'شبكات المجاري': 'Sewer Systems',
  'المياه الصحية': 'Healthy Water',
  'تمديدات منزلية': 'Home Systems',
  الموبيليا: 'Furniture',
  'الابواب الخشبية': 'Wooden Doors',
  الطوبار: 'Building',
  القصارة: 'Plastering',
  البلاط: 'Flagstone',
  'ميكانيكا السيارات': 'Auto Mechanics',
  'كهرباء السيارات': 'Auto Electricity',
  'الكهرباء العامة': 'General Electricity',
  'كهرباء المنازل': 'Home Electricity',
  'الطاقة المتجددة': 'Renewable Energy Systems',
  دهانات: 'Paints',
  'دهانات الحديد': 'Metals Painting',
  'دهانات الاخشاب': 'Wood Painting',
  الجبس: 'Gypsum Painting',
  'دراي كلين': 'Dry Clean',
  'تنضيف السجاد': 'Carpet Cleaning',
  'تنظيف المؤسسات': 'Institutions Cleaning',
  'زراعة الاشجار': 'Tree Planting',
  'تشتيل المزارع': 'Garding',
  'رش المبيدات': 'Pesticide Spraying',
  'بيع الاقمشة': 'Fabrics Selling',
  الخياطة: 'Sewing',
  'تفصيل الملابس': 'Clothes Tailoring',
  'edit-profile': 'Edit Profile',
  'edit-button': 'Edit',
};

export default en;
