const en = {
  title: 'Hello World',
  'home-greeting': 'Home Page',
  'profile-greeting': 'Profile Page',
  'search-greeting': 'Search Page',
  'signUp-greeting': 'Sign Up Page',
  'logIn-greeting': 'Log In Page',
  notFound: 'Not Found Page',
  'home-main-services': 'The services we provide.',
  contactMe: 'Contact me',
  'Phone-Number': 'Phone Number',
  'write-review': 'Write a review please',

  review: 'Add a review',
  'add-review': 'Add a review',
  'review-message': 'Review added successfully',
  'add-phoneNumber': 'Please add your phone number',
  'review-exists': 'You have already added a review',
  'content is required': 'Please enter the content',
  'review-error': 'Please add a review',
  'server-error': 'Internal Server Error',
  ok: 'Ok',
  Cancel: 'Cancel',
  servicesOffer: 'The services I offer',
  'what-they-say-about-us': 'What they said about us !',
  'user does not exist': 'User does not exist',
  'home-search-location': 'Search By location',
  'home-search-word': 'Search',
  'home-search-specific-location': 'Example: بيت حانون',
  'home-welcome-search': 'Search for the most suitable craftsman to get everything you need done.',
  city: 'choose the city',
  'home-search-name': 'Search for the name of craftsman',
  'home-join-us': 'Join the world of craftsmen now',
  'home-join-us-description': 'Register now and become a member of our community and offer your services to business owners',
  'home-join-us-button': 'Register Now',
  'error-heading': 'There is ERROR occurred',
};

export default en;
